### ISSUE TITLE
Ad-Hocing with Pis

### ISSUE THREAD

**Issue by shantanoo-desai** [ComNets-Bremen/HOWTOs#1]
Would love to contribute to this repo! For enthusiasts in Ad-Hoc mode at home or even at work?

Permission granted @asangau ? 

If yes will add a Pull-Request to the repo? 

If you want an insight I have the [Wiki](https://github.com/ComNets-Bremen/TWIN/wiki) for TWIN explaining it how to do the setup!

**Comment by jdede** [comment]
+1
Feel free to create a PR
